name: Deploy to Ubuntu Server
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Creating a maven build
      run: |
        chmod +x ./mvnw
        ./mvnw package
    - name: Set SSH key permissions 
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa    # 환경설정 변수명 SERVER_SSH_KEY <-- 이건 자유
        chmod 600 ~/.ssh/id_rsa
    - name: Add SSH key  #액션을 이용하여 개인키 만드는 부분
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}  #해당 깃허브 리파지토리 셋팅에서 secrets에 개발서버 공개키 등록 id_rsa.pub,  authorized_keys에도 등록
        #/etc/ssh/sshd_config 에서 sudo 로 열어서 PubkeyAuthentication yes 옵션 활성화
    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 ec2-43-203-240-71.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts  # known_hosts에 서버 아이피에 관한것을 등록해주는 작업
        #              알고리즘  운영서버 주소
    - name: Deploy to Server
      run: scp target/*.jar ubuntu@ec2-43-203-240-71.ap-northeast-2.compute.amazonaws.com:~/    

    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@ec2-43-203-240-71.ap-northeast-2.compute.amazonaws.com << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/*.jar > log.txt 2>&1 &
        EOF
      
       
      
